version: '3'
services:
  app:
    build: .
    stdin_open: true  # Enable interaction with standard input
    tty: true         # Allocate a pseudo-TTY
    # db is in the db folder
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33060:3306"
